name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, bcmath, xml
        coverage: none

    - name: Install MySQL Service
      run: sudo apt-get update && sudo apt-get install -y mysql-server

    - name: Start MySQL Service
      run: sudo service mysql start

    - name: Reset MySQL Root Password (Bypass Authentication)
      run: |
        sudo service mysql stop
        sudo mysqld_safe --skip-grant-tables &
        sleep 5
        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root_password'; FLUSH PRIVILEGES;"
        sudo service mysql restart

    - name: Set up MySQL Database
      run: |
        sudo mysql -u root -p'root_password' -e "CREATE DATABASE testing;"
        sudo mysql -u root -p'root_password' -e "CREATE USER 'test_user'@'localhost' IDENTIFIED BY 'test_password';"
        sudo mysql -u root -p'root_password' -e "GRANT ALL PRIVILEGES ON testing.* TO 'test_user'@'localhost';"
        sudo mysql -u root -p'root_password' -e "FLUSH PRIVILEGES;"

    - name: Create .env File
      run: cp .env.example .env

    - name: Configure .env File
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=testing" >> .env
        echo "DB_USERNAME=test_user" >> .env
        echo "DB_PASSWORD=test_password" >> .env

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: testing
        DB_USERNAME: test_user
        DB_PASSWORD: test_password
      run: php artisan test
